version: '2.4'
services:
   birthday-buddy:
    build: ./
    container_name: birthday-buddy
    env_file:
      - src/.env.development
      - src/.env.development.local
    image: ghcr.io/swiizyy/birthday-buddy:latest
    networks:
      - birthday-buddy
    ports:
      - '8282:8282'
    restart: always
    tty: true
    logging:
      options:
        max-size: '1g'
        max-file: '3'

volumes:

networks:
  birthday-buddy: