name: Continuous Delivery

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'Dockerfile'
      - '.github/workflows/continuous-delivery.yml'
      - 'package.json'
  pull_request:
    paths:
      - 'src/**'
      - 'Dockerfile'
      - '.github/workflows/continuous-delivery.yml'
      - 'package.json'

jobs:
  publish:
    name: Publish to GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: |
            ${{ github.event_name == 'pull_request' && format('ghcr.io/swiizyy/birthday-buddy:pr-{0}', github.event.number) || 'ghcr.io/swiizyy/birthday-buddy:latest' }}
