name: Publish Stable

on:
  workflow_dispatch:
    inputs:
      commit:
        type: string
        required: true
        description: The SHA256 commit hash to publish

jobs:
  Publish:
    name: Publish to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.9.0
        with:
          push: true
          context: .
          tags: ghcr.io/${{ github.repository_owner }}/birthday-buddy:latest